# Use the official Nginx image as base image
FROM nginx:latest

# Remove the default nginx configuration file
RUN rm /etc/nginx/conf.d/default.conf
RUN ln -s /etc/nginx/sites-available/nginx.conf /etc/nginx/sites-enabled/nginx.conf
# RUN rm /etc/nginx/nginx.conf
# RUN rm /etc/nginx/conf.d/nginx.conf

# Copy the custom nginx configuration file to the container

# Expose port 80 to the Docker host, so we can access the NGINX webserver
EXPOSE 80

# Start NGINX in the foreground
CMD ["nginx", "-g", "daemon off;"]